### ISSUE TITLE
Не отображается ссылка «теги» в заголовке.

### ISSUE THREAD

**Issue by obukhow** [artpolikarpov/fresh#2]
В общем, в заголовке страницы не отображалась ссылка «Теги», хотя теги присутствуют. Переключал по други темам, и оказалось, что там ссылка показывается. Посмотрел исходники Вашей темы, с ней вроде всё нормально. Полез в ядро «Эгеи», и нашёл там интересный урл ```tags/:tag/pin```. Вызвал его для одного из тегов, и в Вашей теме появилась ссылка «Теги». Никакого интерфейса в котором используется это урл не нашёл. Получается, что для новых блогов использование Вашей темы связано с некоторыми трудностями. Может сама функция добавления тегов в избранное уже устарела и не используется, но Ваша тема всё ещё косвенно её использует.

**Comment by Sogl** [comment]
Подтверждаю проблему. Писал автору на gmail об этом и ответа не получил.

obukhov, Вы как-то решили проблему отображения тегов?

**Comment by artpolikarpov** [comment]
Скоро исправим, там не хватало информации от движка для проверки, есть ли теги вообще, а не только запиненые.

**Comment by Sogl** [comment]
А когда приблизительно будет исправлено? Месяц прошел и ничего не слышно.

**Comment by online** [comment]
@artpolikarpov подскажите, пожалуйста, когда планируете зарелизить исправление по описанной проблеме?

**Comment by obukhow** [comment]
@Sogl @online решил проблему в базе в таблице `e2BlogKeywords` поставив для одного из тегов значение 1 в поле isFavourite (можно поставить для любого)

**Comment by online** [comment]
@obukhow то есть просто ставишь это значение один раз и проблема раз и навсегда исправлена? :wink:

**Comment by obukhow** [comment]
@online абсолютно верно :+1:

**Comment by online** [comment]
@obukhow спасибо, помогло :+1:

**Comment by artpolikarpov** [comment]
Поправил, наконец: https://github.com/artpolikarpov/fresh/commit/1f8f195ddc849de4e2efe56ce707eeeea0d1ff34

Начиная с v2854 (скоро выложу) эта строчка возвращает `false`, если тегов нет вообще.

**Comment by Sogl** [comment]
А как можно сделать, чтобы заработал переключатель важности тегов как у АП в блоге?
http://artpolikarpov.ru/tags/

**Comment by online** [comment]
@Sogl мне кажется, что этот переключатель появляется как только у автора блога накапливается очень много тегов, либо если одни теги используются чаще, чем другие.

**Comment by obukhow** [comment]
@Sogl появляется, если тегов больше 50

**Comment by online** [comment]
@obukhow :+1:

**Comment by Sogl** [comment]
@obukhow Благодарю.
Складывается ощущение, что это Вы делали шаблон =))

А статьи, как я понял, автоматически суммируются. Чем больше одних и тех же тегов - тем они "важнее".

**Comment by obukhow** [comment]
@Sogl это стандартная фича. А на самом деле я просто смотрел исходны код движка, там как ни странно, всё написано ))
