### ISSUE TITLE
Социокнопки не отображаются

### ISSUE THREAD

**Issue by Defite** [artpolikarpov/fresh#4]
Выглядит примерно так.
![2015-01-16 12-06-18 deus ex human revolution](https://cloud.githubusercontent.com/assets/299118/5773834/3bf19532-9d78-11e4-8bf2-bb4e46b29949.png)
Из беглого просмотра стало понятно, что потерялся плагин социолайков. Вернул назад функционал исправлением notes.tmpl.php:

1) Поменял вызов библиотеки с 'social-likes' на 'likely'

```
<?php _LIB ('likely') ?>
```

2) Класс в обертке социокнопок также нужно поменять с 'social-likes' на 'likely'.

Артем, нужно сделать пулл-реквест или ты сам поправишь?

**Comment by online** [comment]
Уже [делали](https://github.com/artpolikarpov/fresh/pull/3) пулл-реквест.

**Comment by Defite** [comment]
Поленился посмотреть в пулл-реквесты, ок.

**Comment by online** [comment]
@Defite осталось дождаться пока Артём примет пулл-реквест :wink:

**Comment by Defite** [comment]
@online ага. Я пока у себя пофиксил.
