### ISSUE TITLE
Текст не виден полностью, вместо части текста — троеточие

### ISSUE THREAD

**Issue by online** [artpolikarpov/fresh#5]
Здравствуйте, Артём!

Подскажите, пожалуйста, как победить одну проблему, с которой столкнулся при использовании вашей замечательной темы. 

Пишу пост и в тексте мне необходимо указать путь реестра: `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation`, но как только я начинаю ресайзить окно браузера, либо смотрю на такой пост через мобильное устройство, то текст обрезается и вместо концовки я вижу троеточие.

Вот, даже скринкаст заснял: http://youtu.be/40bc2RTBpMs

Как мне побороть эту проблему?

**Comment by Sogl** [comment]
@online , Вживую бы на стили посмотреть.

**Comment by online** [comment]
@Sogl, так там всё дефолтное, но могу опубликовать такой пост у себя в блоге, если нужно.

**Comment by Sogl** [comment]
@online , опубликуйте

**Comment by online** [comment]
@Sogl, ок, сделаю в ближайшее время и оставлю здесь ссылку. Спасибо, что откликнулись.

**Comment by online** [comment]
@Sogl, извините за задержку с ответом, вот [ссылка](http://mydb.ws/all/v-windows-sbivaetsya-vremya-posle-raboty-v-ubuntu/) на публикацию, где можно увидеть обсуждаемый баг. Специально залил дефолтную тему и активировал её.

**Comment by Sogl** [comment]
@online, я думаю, что проблема вызвана слишком длинным словом, которое составляет запись ветки реестра. Как понимаете, в вебе переносы автоматически не расставляются, исключая случаи со специально созданными для этого js-библиотеками.

Грязный хак - просто добавить пробел(ы) в середине ветки. 
Или, как вариант, разместить в блоке с кодом, где есть горизонтальная прокрутка.

Рабочее решение - заключить ветку в span со стилем:
```
.myspan {
    word-wrap: break-word;
}
```
В итоге получите побуквенный перенос. В данном случае это не критично.

**Comment by online** [comment]
@Sogl, большое спасибо, Артём. Ваше решение реально помогло решить описанную проблему :wink:

**Comment by Sogl** [comment]
@online, Не за что. Думаю, issue можно закрыть.

**Comment by online** [comment]
@Sogl, да, можно закрывать.
