### ISSUE TITLE
Likely

### ISSUE THREAD

**Issue by skurudo** [artpolikarpov/fresh#6]
Доброго дня.
Есть ли возможность добавить в тему свежие социокнопки?
http://ilyabirman.ru/projects/likely/

**Comment by Sogl** [comment]
Все давно добавлено.
Смотрим сюда и правим у себя, если нужно:
https://github.com/artpolikarpov/fresh/pull/3

**Comment by online** [comment]
@skurudo, ещё вот такой материал нашёл — «[Добавляем в Эгею кнопку Google+](http://mydb.ws/all/dobavlyaem-v-egeyu-knopku-google/)». Может вам пригодится.

**Comment by skurudo** [comment]
@online @Sogl спасибо :)
